version: 2.1
executors:
  base:
    docker:
      - image: cimg/python:3.10

jobs:
  test:
    executor: base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Nginx proxy and webserver.
          command: |
            docker compose up --build -d       
      - run:
          name: Quickly check to make sure Nginx is up and redirecting.
          command: |
            set -x
            docker run --network container:nginx_proxy \
              appropriate/curl -4 --retry 10 --retry-delay 3 --retry-connrefused --insecure https://localhost/
  deploy-nginx:
    executor: base
    parameters:
      docker_repo:
        type: string
      ecr_repo:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run: pip install awscli pip --upgrade
      - run:
          name: Build nginx image
          command: |
            docker build --build-arg "NGINX_VERSION=${NGINX_VERSION:-latest}" --build-arg "COMMIT=${CIRCLE_SHA1}" -t nginx-dynamic-acm -t "nginx-dynamic-acm:ci${CIRCLE_BUILD_NUM}" . --progress plain
      - run:
          name: Create Nginx proxy and webserver.
          command: |
            docker compose up -f docker-compose-ci.yaml -d
      - run:
          name: Quickly check to make sure Nginx is up and redirecting.
          command: |
            set -x
            docker run --network container:nginx_proxy \
              appropriate/curl -4 --retry 10 --retry-delay 3 --retry-connrefused --insecure https://localhost/
      - run:
          name: Push to Dockerhub and AWS ECR on master or prod
          command: |
            bash ./publish.sh "<< pipeline.git.branch >>" "<< parameters.docker_repo >>" "<< parameters.ecr_repo >>"

workflows:
  version: 2
  build:
    jobs:
      # - test
      - deploy-nginx:
          docker_repo: radaisystems/nginx-dynamic-acm
          ecr_repo: 659386482123.dkr.ecr.us-west-2.amazonaws.com/radai_nginx_dynamic_acm
          context:
            - AWS_PROD_ACCOUNT_CIRCLECI_USER_IAM
            - DOCKERHUB_RADAISYSTEMSMACHINEUSER
