version: 2.1
orbs: 
  aws-cli: circleci/aws-cli@3.1.1
executors:
  base:
    docker:
      - image: cimg/base:2022.08

jobs:
  deploy-nginx:
    executor: base
    parameters:
      docker_repo:
        type: string
      ecr_repo:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build nginx image
          command: |
            docker build -t nginx-dynamic-acm . --progress plain
      - run:
          name: Push to Dockerhub and AWS ECR on master or prod
          command: |
            bash ./publish.sh "<< pipeline.git.branch >>" "<< parameters.docker_repo >>" "<< parameters.ecr_repo >>"

workflows:
  version: 2
  build:
    jobs:
      - deploy-nginx:
          docker_repo: radaisystems/nginx-dynamic-acm
          ecr_repo: 659386482123.dkr.ecr.us-west-2.amazonaws.com/radai_nginx_dynamic_acm
          context:
            - AWS_PROD_ACCOUNT_CIRCLECI_USER_IAM
