name: Deploy Nginx

on:
  push:
    branches:
      - master
      - prod
      - vishad/PLE-1877

jobs:
  deploy-nginx:
    runs-on: nginx-acm-ssl-proxy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install AWS CLI
        run: pip install awscli pip --upgrade

      - name: Build nginx image
        run: |
          docker build --build-arg "NGINX_VERSION=${NGINX_VERSION:-latest}" --build-arg "COMMIT=${{ github.sha }}" -t nginx-dynamic-acm -t "nginx-dynamic-acm:ci${{ github.run_number }}" . --progress plain

      - name: Create Nginx proxy and webserver
        run: |
          docker compose -f docker-compose-ci.yaml up -d

      - name: Quickly check to make sure Nginx is up and redirecting
        run: |
          set -x
          docker run --network container:nginx_proxy \
            appropriate/curl -4 --retry 10 --retry-delay 3 --retry-connrefused --insecure https://localhost/

      - name: Push to Artifactory and AWS ECR on master/prod branch
        run: |
          bash -x ./publish.sh "${{ github.ref_name }}" "radaisystems/nginx-dynamic-acm" "659386482123.dkr.ecr.us-west-2.amazonaws.com/radai_nginx_dynamic_acm"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
